### PR TITLE
Add a version of begin() that allows you to indicate the character set

### PR DESCRIPTION
**Pull request by camilstaps**
This allows you to use for example:

```
lcd.begin(16, 2, LCD_EUROPEAN_II);
```

### CODE REVIEW

**Comment by camilstaps** [comment]
@ladyada Could you have a look at this PR, please? I believe it is backwards-compatible and it would be great to have this easily available when people download the library.

**Comment by ladyada** [comment]
hi thanks for the PR! :)
could you make this one function instead of two, with the third argument having a default value?

**Comment by camilstaps** [comment]
@ladyada thanks for the quick response! I've added a new commit, but feel free to squash of course.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
nice!

**Pull request merged**
